document.getElementById('generateJoke').addEventListener('click', function() {
    var jokes = [
        "Yo Mama's so stupid, she put two quarters in her ears and thought she was listening to 50 Cent.",
        "Yo Mama's so fat, when she goes camping, the bears hide their food.",
        "Yo Mama's so old, she knew Burger King when he was a prince.",
        "Yo Mama's so short, she can do backflips under the bed."
    "Yo Mama's so poor, when I rang the doorbell, she stuck her head out the window and yelled 'DING DONG!'",
    "Yo Mama's so fat, when she wears a yellow raincoat, people yell 'Taxi!'",
    "Yo Mama's so dumb, she thought a quarterback was a refund.",
    "Yo Mama's so fat, her belly button gets home 15 minutes before she does.",
    "Yo Mama's so old, her birth certificate expired.",
    "Yo Mama's so poor, she can't afford to pay attention!",
    "Yo Mama's so stupid, she got hit by a parked car.",
    "Yo Mama's so fat, when she stepped on a scale, it read 'One at a time, please.'",
    "Yo Mama's so ugly, when she tried to join an ugly contest, they said 'Sorry, no professionals.'",
    "Yo Mama's so slow, it took her 2 hours to watch 60 Minutes.",
    "Yo Mama's so fat, when she turns around, people give her a welcome back party!",
    "Yo Mama's so old, she has a picture of Moses in her yearbook.",
    "Yo Mama's so dumb, she thought Dunkin' Donuts was a basketball team.",
    "Yo Mama's so fat, she fell in love and broke it.",
    "Yo Mama's so short, she has to use a ladder to pick up a dime.",
    "Yo Mama's so ugly, even her shadow ran away from her.",
    "Yo Mama's so poor, she waves around a popsicle and calls it air conditioning.",
    "Yo Mama's so old, she remembers when the Grand Canyon was just a ditch.",
    "Yo Mama's so fat, when she wears high heels, she strikes oil.",
    "Yo Mama's so stupid, she put lipstick on her forehead to make up her mind.",
    "Yo Mama's so fat, when she sat on an iPod, she made the iPad!",
    "Yo Mama's so ugly, when she looks in the mirror, her reflection ducks.",
    "Yo Mama's so poor, the ducks throw bread at her.",
    "Yo Mama's so old, she sat next to Moses in third grade.",
    "Yo Mama's so fat, when she wears a red dress, kids yell 'Hey Kool-Aid Man!'",
    "Yo Mama's so ugly, she scared the pattern off the knitting needle.",
    "Yo Mama's so fat, she needs a bookmark to find her belly button.",
    "Yo Mama's so old, she walked out of a museum and the alarm went off.",
    "Yo Mama's so fat, her blood type is Ragu.",
    "Yo Mama's so short, she can play handball on the curb.",
    "Yo Mama's so stupid, she took a ruler to bed to see how long she slept.",
    "Yo Mama's so fat, when she went to the beach, Greenpeace tried to drag her back into the ocean.",
    "Yo Mama's so old, her social security number is 1.",
    "Yo Mama's so ugly, she turned Medusa to stone.",
    "Yo Mama's so fat, when she stepped on the scale it said 'To be continued.'",
    "Yo Mama's so stupid, she put airbags on her computer in case it crashed.",
    "Yo Mama's so fat, she has to iron her pants on the driveway.",
    "Yo Mama's so poor, burglars break into her house and leave money.",
    "Yo Mama's so old, she knew the Flintstones personally.",
    "Yo Mama's so fat, she uses the Equator as her belt.",
    "Yo Mama's so ugly, she made a blind kid cry.",
    "Yo Mama's so fat, she needs cheat codes for Wii Fit.",
    "Yo Mama's so stupid, she climbed over a glass wall to see what was on the other side.",
    "Yo Mama's so poor, she washes paper plates.",
    "Yo Mama's so old, she was a waitress at the Last Supper.",
    "Yo Mama's so fat, when she wears a yellow raincoat, people yell 'Taxi!'",
    "Yo Mama's so ugly, she made an onion cry.",
    "Yo Mama's so fat, her baby pictures were taken by satellite.",
    "Yo Mama's so stupid, she sold her car for gas money.",
    "Yo Mama's so old, when she reads the Bible she reminisces.",
    "Yo Mama's so fat, when she jumped in the air, she got stuck.",
    "Yo Mama's so ugly, the government moved Halloween to her birthday.",
    "Yo Mama's so fat, she sat on a quarter and a booger shot out of George Washington's nose.",
    "Yo Mama's so stupid, she took a spoon to the Super Bowl.",
    "Yo Mama's so old, her birth certificate says 'expired'.",
    "Yo Mama's so fat, she uses a mattress as a maxi pad.",
    "Yo Mama's so ugly, she made a mime scream.",
    "Yo Mama's so fat, when she dances, the band skips.",
    "Yo Mama's so stupid, she thinks menopause is a button on a DVD player.",
    "Yo Mama's so old, her birth certificate is written in hieroglyphics.",
    "Yo Mama's so fat, when she wears a yellow coat, people try to flag her for a taxi.",
    "Yo Mama's so ugly, when she went to a haunted house, she came out with a job application.",
    "Yo Mama's so fat, when she sits around the house, she sits AROUND the house.",
    "Yo Mama's so stupid, she got locked in a grocery store and starved.",
    "Yo Mama's so old, when God said 'Let there be light', she hit the switch.",
    "Yo Mama's so fat, she uses Google Earth to take a selfie.",
    "Yo Mama's so ugly, she gives Freddy Krueger nightmares.",
    "Yo Mama's so fat, she's on both sides of the family.",
    "Yo Mama's so stupid, when she got locked in a bed store, she slept on the floor.",
    "Yo Mama's so old, she owes Jesus a dollar.",
    "Yo Mama's so fat, when she stepped on a scale, it said 'One person at a time, please.'",
    "Yo Mama's so ugly, her portraits hang themselves.",
    "Yo Mama's so fat, when she walks in high heels, she strikes oil.",
    "Yo Mama's so stupid, she thinks a quarterback is a refund.",
    "Yo Mama's so old, she has an autographed Bible.",
    "Yo Mama's so fat, she sat on Walmart and lowered the prices."
    "Yo Mama's so ugly, she looked out the window and got arrested for mooning.",
    "Yo Mama's so fat, she has more curves than a racetrack.",
    "Yo Mama's so stupid, she tried to put M&M's in alphabetical order.",
    "Yo Mama's so old, she co-authored the Ten Commandments.",
    "Yo Mama's so fat, when she gets on the scale it says 'To be continued.'",
    "Yo Mama's so ugly, she scared the crap out of the toilet.",
    "Yo Mama's so fat, when she skips a meal, the stock market drops.",
    "Yo Mama's so stupid, she thought a lawsuit was something you wear to court.",
    "Yo Mama's so old, her birth certificate is in Roman numerals.",
    "Yo Mama's so fat, she can't even jump to a conclusion.",
    "Yo Mama's so ugly, she made a Happy Meal cry.",
    "Yo Mama's so fat, when she goes to the zoo, elephants throw peanuts at her.",
    "Yo Mama's so stupid, she thinks Taco Bell is a Mexican phone company.",
    "Yo Mama's so old, her first Christmas was the first Christmas.",
    "Yo Mama's so fat, when she wears a yellow raincoat, people call her 'Taxi!'",
    "Yo Mama's so ugly, she's the reason why Waldo is hiding.",
    "Yo Mama's so fat, when she fell in love she broke it.",
    "Yo Mama's so stupid, she brought a spoon to the Super Bowl.",
    "Yo Mama's so old, she sat behind Jesus in 3rd grade.",
    "Yo Mama's so fat, she got baptized at Sea World.",
    "Yo Mama's so ugly, even her own reflection refuses to look back.",
    "Yo Mama's so fat, she stepped on a scale and it said 'I want your weight, not your phone number.'",
    "Yo Mama's so stupid, she climbed over a glass wall to see what was on the other side.",
    "Yo Mama's so old, her social security number is 1.",
    "Yo Mama's so fat, when she went to the beach, all the whales started singing 'We Are Family.'"
        // add more jokes here
    ];

    var joke = jokes[Math.floor(Math.random() * jokes.length)];

    document.getElementById('joke').innerText = joke;
});
